const moviesData = [
  {
    id: "hero-1",
    title: "House of the Dragon",
    type: "show",
    category: "trending",
    rating: "9.0",
    year: "2024",
    duration: "2 Seasons",
    genre: "Fantasy, Drama",
    description: "An internal succession war within House Targaryen at the height of its power, 172 years before the birth of Daenerys Targaryen.",
    backdrop: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?q=80&w=1600&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?q=80&w=400&auto=format&fit=crop",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    isPremium: true
  },
  {
    id: "hero-2",
    title: "Shōgun",
    type: "show",
    category: "trending",
    rating: "9.2",
    year: "2024",
    duration: "1 Season",
    genre: "Drama, History, War",
    description: "When a mysterious English ship is found marooned in a nearby fishing village, Lord Yoshii Toranaga discovers secrets that could tip the scales of power.",
    backdrop: "https://images.unsplash.com/photo-1528164344705-47542687000d?q=80&w=1600&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=400&auto=format&fit=crop",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    isPremium: true
  },
  {
    id: "hero-3",
    title: "Loki",
    type: "show",
    category: "trending",
    rating: "8.7",
    year: "2023",
    duration: "2 Seasons",
    genre: "Action, Sci-Fi",
    description: "The mercurial villain Loki resumes his role as the God of Mischief in a new series that takes place after the events of “Avengers: Endgame.”",
    backdrop: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1600&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1635805737707-575885ab0820?q=80&w=400&auto=format&fit=crop",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    isPremium: true
  },
  {
    id: "m-1",
    title: "Avengers: Endgame",
    type: "movie",
    category: "popular-movies",
    rating: "8.4",
    year: "2019",
    duration: "3h 2m",
    genre: "Action, Adventure",
    description: "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more.",
    backdrop: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?q=80&w=1600&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?q=80&w=400&auto=format&fit=crop",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    isPremium: true
  },
  {
    id: "m-2",
    title: "The Lion King",
    type: "movie",
    category: "popular-movies",
    rating: "8.5",
    year: "1994",
    duration: "1h 28m",
    genre: "Animation, Family",
    description: "Lion prince Simba and his father are targeted by his bitter uncle Scar, who wants to ascend the throne himself.",
    backdrop: "https://images.unsplash.com/photo-1546182990-dffeafbe841d?q=80&w=1600&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1535083783855-76ae62b2914e?q=80&w=400&auto=format&fit=crop",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    isPremium: false
  },
  {
    id: "m-3",
    title: "Avatar: The Way of Water",
    type: "movie",
    category: "popular-movies",
    rating: "7.6",
    year: "2022",
    duration: "3h 12m",
    genre: "Sci-Fi, Adventure",
    description: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
    backdrop: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1600&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?q=80&w=400&auto=format&fit=crop",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    isPremium: true
  },
  {
    id: "m-4",
    title: "Toy Story 4",
    type: "movie",
    category: "popular-movies",
    rating: "7.7",
    year: "2019",
    duration: "1h 40m",
    genre: "Animation, Comedy",
    description: "When a new toy called 'Forky' joins Woody and the gang, a road trip alongside old and new friends reveals how big the world can be for a toy.",
    backdrop: "https://images.unsplash.com/photo-1559251606-c623743a6d76?q=80&w=1600&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1560942485-b2a11cc13456?q=80&w=400&auto=format&fit=crop",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    isPremium: false
  },
  {
    id: "s-1",
    title: "The Mandalorian",
    type: "show",
    category: "must-watch-shows",
    rating: "8.7",
    year: "2019",
    duration: "3 Seasons",
    genre: "Sci-Fi, Action",
    description: "The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.",
    backdrop: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=1600&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?q=80&w=400&auto=format&fit=crop",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    isPremium: true
  },
  {
    id: "s-2",
    title: "Modern Family",
    type: "show",
    category: "must-watch-shows",
    rating: "8.5",
    year: "2009",
    duration: "11 Seasons",
    genre: "Comedy, Romance",
    description: "Three different but related families face trials and tribulations in their own uniquely hilarious ways.",
    backdrop: "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?q=80&w=1600&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=400&auto=format&fit=crop",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    isPremium: false
  },
  {
    id: "s-3",
    title: "Grey's Anatomy",
    type: "show",
    category: "must-watch-shows",
    rating: "7.6",
    year: "2005",
    duration: "20 Seasons",
    genre: "Drama, Romance",
    description: "A drama centered on the personal and professional lives of five surgical interns and their supervisors.",
    backdrop: "https://images.unsplash.com/photo-1584515901387-a7f11b22974e?q=80&w=1600&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=400&auto=format&fit=crop",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    isPremium: true
  },
  {
    id: "sp-1",
    title: "ICC Men's T20 World Cup: IND vs PAK",
    type: "sport",
    category: "live-sports",
    rating: "LIVE",
    year: "2026",
    duration: "LIVE NOW",
    genre: "Cricket, T20",
    description: "The ultimate clash in cricket: India takes on Pakistan in the ICC Men's T20 World Cup group stage live from New York.",
    backdrop: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=1600&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1540747737956-37872ba68c5a?q=80&w=400&auto=format&fit=crop",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
    isPremium: false
  },
  {
    id: "sp-2",
    title: "Premier League: Chelsea vs Arsenal",
    type: "sport",
    category: "live-sports",
    rating: "LIVE",
    year: "2026",
    duration: "LIVE NOW",
    genre: "Football, Soccer",
    description: "London Derby clash at Stamford Bridge as Chelsea host rivals Arsenal in a vital Premier League encounter.",
    backdrop: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=1600&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1518063319789-7217e6706b04?q=80&w=400&auto=format&fit=crop",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    isPremium: true
  },
  {
    id: "sp-3",
    title: "Wimbledon Men's Singles Final",
    type: "sport",
    category: "live-sports",
    rating: "Replay",
    year: "2025",
    duration: "3h 45m",
    genre: "Tennis, Grand Slam",
    description: "Relive the historic men's singles final clash at the All England Club with intense rallies and premium tennis action.",
    backdrop: "https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?q=80&w=1600&auto=format&fit=crop",
    poster: "https://images.unsplash.com/photo-1592709823125-a191f07a2a5e?q=80&w=400&auto=format&fit=crop",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    isPremium: true
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = moviesData;
}
